### ISSUE TITLE
Unable to add package to Unity

### ISSUE THREAD

**Issue by MDTxxx** [heathen-engineering/BGSDK-Foundation#1]
I'm unable to import the package to Unity 2020.1.0f1 neither using the recommended "Add from git URL..." nor from the disk using the "package.json" file.

I get error on git URL import:

> Cannot perform upm operation: Unable to add package [https://github.com/heathen-engineering/Arkane-Foundation.git]:
>   No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound].See console for more details
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

I have both Git Desktop and Git for Unity package installed.

I get error on disk import:

> Cannot perform upm operation: Unable to add package [file:C:/Users/medit/Downloads/BGSDK-Foundation-master]:
>   Manifest [C:\Users\medit\Downloads\BGSDK-Foundation-master\package.json] is invalid:
>     Version '0.3' is invalid. Expected a 'SemVer' compatible value. [NotFound].See console for more details
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by JamesMcGhee** [comment]
Issue was a change Unity made requiring a 3 part version number.
We only used 2 part ... that has been updated now.

Also you can pull in via standard unity package as well we have that set up under the releases.

**Comment by dblatner** [comment]
Hi @JamesMcGhee , the fix for Unity 2020+ makes this package incompatible with Unity 2018+.

My suggestion is to make a separate branch for Unity 2019 (and/or 2018) where the 2-part version notation is used in `package.json`.

The Readme tells compatibility with Unity 2018+.
